// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "button": {
      name: "button",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/ui/button")),
      source: "",
      files: ["registry/default/ui/button.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
  },  "new-york": {
    "button": {
      name: "button",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/new-york/ui/button")),
      source: "",
      files: ["registry/new-york/ui/button.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
  },
}
