// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react";

export const Index: Record<string, any> = {
  components: {
    avatar: {
      name: "avatar",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(
        () => import("@/../../packages/ui/src/components/avatar"),
      ),
      source: "",
      files: ["@/../../packages/ui/src/components/avatar.tsx"],
      category: "undefined",
      subcategory: "undefined",
    },
    badge: {
      name: "badge",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(
        () => import("@/../../packages/ui/src/components/badge"),
      ),
      source: "",
      files: ["@/../../packages/ui/src/components/badge.tsx"],
      category: "undefined",
      subcategory: "undefined",
    },
    button: {
      name: "button",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(
        () => import("@/../../packages/ui/src/components/button"),
      ),
      source: "",
      files: ["@/../../packages/ui/src/components/button.tsx"],
      category: "undefined",
      subcategory: "spinner",
    },
    checkbox: {
      name: "checkbox",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(
        () => import("@/../../packages/ui/src/components/checkbox"),
      ),
      source: "",
      files: ["@/../../packages/ui/src/components/checkbox.tsx"],
      category: "undefined",
      subcategory: "undefined",
    },
    input: {
      name: "input",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(
        () => import("@/../../packages/ui/src/components/input"),
      ),
      source: "",
      files: ["@/../../packages/ui/src/components/input.tsx"],
      category: "undefined",
      subcategory: "undefined",
    },
    select: {
      name: "select",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(
        () => import("@/../../packages/ui/src/components/select"),
      ),
      source: "",
      files: ["@/../../packages/ui/src/components/select.tsx"],
      category: "undefined",
      subcategory: "undefined",
    },
    spinner: {
      name: "spinner",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(
        () => import("@/../../packages/ui/src/components/spinner"),
      ),
      source: "",
      files: ["@/../../packages/ui/src/components/spinner.tsx"],
      category: "undefined",
      subcategory: "undefined",
    },
    switch: {
      name: "switch",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(
        () => import("@/../../packages/ui/src/components/switch"),
      ),
      source: "",
      files: ["@/../../packages/ui/src/components/switch.tsx"],
      category: "undefined",
      subcategory: "undefined",
    },
    textarea: {
      name: "textarea",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(
        () => import("@/../../packages/ui/src/components/textarea"),
      ),
      source: "",
      files: ["@/../../packages/ui/src/components/textarea.tsx"],
      category: "undefined",
      subcategory: "undefined",
    },
    tooltip: {
      name: "tooltip",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(
        () => import("@/../../packages/ui/src/components/tooltip"),
      ),
      source: "",
      files: ["@/../../packages/ui/src/components/tooltip.tsx"],
      category: "undefined",
      subcategory: "undefined",
    },
  },
};
